apiVersion: v1
kind: Pod
metadata:
  name: app-node
spec:
  containers:
    - name: app-node
      image: bayembacke221/app-node:v1
      imagePullPolicy: Always 
      resources:
        limits:
          memory: "200Mi"
          cpu: "0.5"
